import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;


public class main extends javax.swing.JFrame  {

    /**
     * Creates new form loginScreen
     */
    public main() {
        initComponents();
        
        
        studentLayout = (CardLayout)(studentContent.getLayout());
        studentLayout.addLayoutComponent(studentHomePage, "studentHomePage");
        studentLayout.addLayoutComponent(studentDetailsPanel, "studentDetailsPanel");
        studentLayout.addLayoutComponent(jPanel3, "jPanel3");
        
        staffLayout = (CardLayout) (staffContent.getLayout());
        staffLayout.addLayoutComponent(staffHomePage,"staffHomePage");
        staffLayout.addLayoutComponent(staffDetailsPanel, "staffDetailsPanel");
        staffLayout.addLayoutComponent(staffUserListPanel, "staffUserListPanel");
        
        adminLayout = (CardLayout)(adminContent.getLayout());
        adminLayout.addLayoutComponent(adminHomePage, "adminHomePage");
        adminLayout.addLayoutComponent(adminUserListPanel, "adminUserListPanel");
        adminLayout.addLayoutComponent(adminAddUserPanel, "adminAddUserPanel");
        adminLayout.addLayoutComponent(adminCourseListPanel, "adminCourseListPanel");
        adminLayout.addLayoutComponent(adminAddCoursePanel, "adminAddCoursePanel");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        loginScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginIDField = new javax.swing.JTextField();
        loginPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        loginLogo = new javax.swing.JLabel();
        loginErrorMessage = new javax.swing.JLabel();
        mainStudent = new javax.swing.JPanel();
        logoutButtonStudent = new javax.swing.JButton();
        studentDetailsButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        studentContent = new javax.swing.JPanel();
        studentHomePage = new javax.swing.JPanel();
        studentHomeLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        studentDetailsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        studentDetailSurnameLabel = new javax.swing.JLabel();
        studentDetailAddressLabel = new javax.swing.JLabel();
        studentDetailEmailLabel = new javax.swing.JLabel();
        studentDetailSemesterLabel = new javax.swing.JLabel();
        studentDetailYearLabel = new javax.swing.JLabel();
        studentDetailECTSLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        studentDetailNameLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        studentDetailIDLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        studentDetailPhoneLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        studentLogo = new javax.swing.JLabel();
        mainStaff = new javax.swing.JPanel();
        staffContent = new javax.swing.JPanel();
        staffHomePage = new javax.swing.JPanel();
        staffHomeLogo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        staffDetailsPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        staffDetailNameLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        staffDetailIDlabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        staffDetailAddressLabel = new javax.swing.JLabel();
        staffDetailEmailLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        staffDetailSurnameLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        staffDetailPhoneLabel = new javax.swing.JLabel();
        staffUserListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffUserTable = new javax.swing.JTable();
        logoutButtonStaff = new javax.swing.JButton();
        staffDetailsButton = new javax.swing.JButton();
        staffLogo = new javax.swing.JLabel();
        staffUserListButton = new javax.swing.JButton();
        mainAdmin = new javax.swing.JPanel();
        adminContent = new javax.swing.JPanel();
        adminHomePage = new javax.swing.JPanel();
        adminHomeLogo = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        adminUserListPanel = new javax.swing.JPanel();
        adminAddUserButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminUserTable = new javax.swing.JTable();
        adminAddUserPanel = new javax.swing.JPanel();
        adminBacktoUserListButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        adminAddStudentPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        adminAddStudentIDField = new javax.swing.JTextField();
        adminAddStudentSurnameField = new javax.swing.JTextField();
        adminAddStudentNameField = new javax.swing.JTextField();
        adminAddStudentPasswordField = new javax.swing.JTextField();
        adminAddStudentAddressField = new javax.swing.JTextField();
        adminAddStudentEmailField = new javax.swing.JTextField();
        adminAddStudentPhoneField = new javax.swing.JTextField();
        adminAddStudentYearField = new javax.swing.JTextField();
        adminAddStudentSemesterField = new javax.swing.JTextField();
        adminAddStudentECTSField = new javax.swing.JTextField();
        adminAddStudentButton = new javax.swing.JButton();
        adminAddStudentErrorMessage = new javax.swing.JLabel();
        adminAddStaffPanel = new javax.swing.JPanel();
        adminAddAdminPanel = new javax.swing.JPanel();
        adminCourseListPanel = new javax.swing.JPanel();
        adminAddCourseButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        adminCourseTable = new javax.swing.JTable();
        adminAddCoursePanel = new javax.swing.JPanel();
        adminBackToCourseListButton = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        adminAddCourseIDField = new javax.swing.JTextField();
        adminAddCourseNameField = new javax.swing.JTextField();
        adminAddCourseECTSField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        adminAddCourseInfoField = new javax.swing.JTextArea();
        adminAddCourseLecturerField = new javax.swing.JComboBox<>();
        adminAddCourseFinalButton = new javax.swing.JButton();
        adminAddCourseSemesterField = new javax.swing.JComboBox<>();
        adminAddCourseErrorMessage = new javax.swing.JLabel();
        logoutButtonAdmin = new javax.swing.JButton();
        adminLogo = new javax.swing.JLabel();
        adminUserListButton = new javax.swing.JButton();
        adminCourseListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 204));
        setForeground(new java.awt.Color(204, 0, 204));
        setName("loginFrame"); // NOI18N

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        loginScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        loginScreen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, 20));

        jLabel2.setText("Password");
        loginScreen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 110, 20));

        loginIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIDFieldActionPerformed(evt);
            }
        });
        loginIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginIDFieldKeyPressed(evt);
            }
        });
        loginScreen.add(loginIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 170, 30));

        loginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordFieldActionPerformed(evt);
            }
        });
        loginPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginPasswordFieldKeyPressed(evt);
            }
        });
        loginScreen.add(loginPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 170, 30));

        loginButton.setText("Login");
        loginButton.setActionCommand("loginButton");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginScreen.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 140, 30));
        loginButton.getAccessibleContext().setAccessibleName("loginButton");

        loginScreen.add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 520, 190));
        ImageIcon icon = new ImageIcon("./images/logo-Main.png");
        loginLogo.setIcon(icon);

        loginErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        loginScreen.add(loginErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 330, 20));

        jLayeredPane1.add(loginScreen, "card2");

        mainStudent.setBackground(new java.awt.Color(153, 153, 153));
        mainStudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButtonStudent.setText("Logout");
        logoutButtonStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonStudentActionPerformed(evt);
            }
        });
        mainStudent.add(logoutButtonStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 40));

        studentDetailsButton.setText("Personal Details");
        studentDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDetailsButtonActionPerformed(evt);
            }
        });
        mainStudent.add(studentDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainStudent.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 20));

        studentContent.setLayout(new java.awt.CardLayout());

        jLabel5.setText("A Java Swing project by");

        jLabel6.setText("- Apostolidis Mixalis -");

        jLabel7.setText("- Kaloudis Alexandros - ");

        jLabel8.setText("- Pavlidis Giorgos -");

        javax.swing.GroupLayout studentHomePageLayout = new javax.swing.GroupLayout(studentHomePage);
        studentHomePage.setLayout(studentHomePageLayout);
        studentHomePageLayout.setHorizontalGroup(
            studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentHomePageLayout.createSequentialGroup()
                .addGroup(studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentHomePageLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(studentHomePageLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel6)))))
                    .addGroup(studentHomePageLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentHomePageLayout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addComponent(studentHomeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        studentHomePageLayout.setVerticalGroup(
            studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentHomePageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(studentHomeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        studentHomeLogo.setIcon(icon);

        studentContent.add(studentHomePage, "card4");

        studentDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Surname:");
        studentDetailsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 40));

        jLabel11.setText("Phone Number:");
        studentDetailsPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel12.setText("Address:");
        studentDetailsPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel13.setText("E-mail:");
        studentDetailsPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel14.setText("Year of Entry:");
        studentDetailsPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 90, 20));

        jLabel15.setText("Semester: ");
        studentDetailsPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 60, 40));

        jLabel16.setText("ECTS:");
        studentDetailsPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        studentDetailSurnameLabel.setBackground(new java.awt.Color(204, 204, 204));
        studentDetailsPanel.add(studentDetailSurnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, 40));

        studentDetailAddressLabel.setBackground(new java.awt.Color(204, 204, 204));
        studentDetailsPanel.add(studentDetailAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 230, 30));

        studentDetailEmailLabel.setBackground(new java.awt.Color(204, 204, 204));
        studentDetailsPanel.add(studentDetailEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 230, 30));

        studentDetailSemesterLabel.setBackground(new java.awt.Color(204, 204, 204));
        studentDetailsPanel.add(studentDetailSemesterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 150, 40));

        studentDetailYearLabel.setBackground(new java.awt.Color(204, 204, 204));
        studentDetailsPanel.add(studentDetailYearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 150, 20));

        studentDetailECTSLabel.setBackground(new java.awt.Color(204, 204, 204));
        studentDetailsPanel.add(studentDetailECTSLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 150, 40));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 40));

        studentDetailNameLabel.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(studentDetailNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 150, 40));

        jLabel10.setText("Student ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 40));

        studentDetailIDLabel.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(studentDetailIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 150, 40));

        studentDetailsPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 40));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentDetailPhoneLabel.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(studentDetailPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 150, 40));

        studentDetailsPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 710, 40));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        studentDetailsPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 710, 40));

        studentContent.add(studentDetailsPanel, "card2");

        jLabel4.setText("Panel 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        studentContent.add(jPanel3, "card3");

        mainStudent.add(studentContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 710, 460));

        studentLogo.setIcon(mini);
        studentLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLogoMouseClicked(evt);
            }
        });
        mainStudent.add(studentLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, 50));

        jLayeredPane1.add(mainStudent, "card3");

        mainStaff.setBackground(new java.awt.Color(153, 153, 153));
        mainStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffContent.setLayout(new java.awt.CardLayout());

        staffHomeLogo.setIcon(icon);

        jLabel20.setText("A Java Swing project by:");

        jLabel40.setText("- Apostolidis Mixalis ");

        jLabel41.setText("- Kaloudis Alexandros");

        jLabel42.setText("- Pavlidis Giorgos");

        javax.swing.GroupLayout staffHomePageLayout = new javax.swing.GroupLayout(staffHomePage);
        staffHomePage.setLayout(staffHomePageLayout);
        staffHomePageLayout.setHorizontalGroup(
            staffHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffHomePageLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(staffHomeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(staffHomePageLayout.createSequentialGroup()
                .addGroup(staffHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffHomePageLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(staffHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel40)
                            .addGroup(staffHomePageLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel42))))
                    .addGroup(staffHomePageLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staffHomePageLayout.setVerticalGroup(
            staffHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffHomePageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(staffHomeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        staffContent.add(staffHomePage, "card3");

        staffDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Name:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 40, -1));
        jPanel5.add(staffDetailNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 105, 14));

        jLabel22.setText("Staff ID:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 53, -1));
        jPanel5.add(staffDetailIDlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 15, 116, 14));

        staffDetailsPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 40));

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Address");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 47, 18));
        jPanel6.add(staffDetailAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 11, 117, 18));
        jPanel6.add(staffDetailEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 11, 200, 14));

        jLabel21.setText("E-mail:");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 70, -1));

        staffDetailsPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 710, 40));

        jLabel18.setText("Surname:");
        staffDetailsPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        staffDetailsPanel.add(staffDetailSurnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 20));

        jLabel24.setText("Phone Number:");
        staffDetailsPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));
        staffDetailsPanel.add(staffDetailPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 180, 20));

        staffContent.add(staffDetailsPanel, "card2");

        staffUserListPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Surname", "Name", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        staffUserTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        staffUserTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(staffUserTable);

        staffUserListPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        staffContent.add(staffUserListPanel, "card4");

        mainStaff.add(staffContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 700, 460));

        logoutButtonStaff.setText("Logout");
        logoutButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonStaffActionPerformed(evt);
            }
        });
        mainStaff.add(logoutButtonStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 40));

        staffDetailsButton.setText("Personal Details");
        staffDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffDetailsButtonActionPerformed(evt);
            }
        });
        mainStaff.add(staffDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 20));

        staffLogo.setIcon(mini);
        staffLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffLogoMouseClicked(evt);
            }
        });
        mainStaff.add(staffLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, 50));

        staffUserListButton.setText("User List");
        staffUserListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffUserListButtonActionPerformed(evt);
            }
        });
        mainStaff.add(staffUserListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, -1));

        jLayeredPane1.add(mainStaff, "card4");

        mainAdmin.setBackground(new java.awt.Color(153, 153, 153));
        mainAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminContent.setLayout(new java.awt.CardLayout());

        adminHomeLogo.setIcon(icon);

        jLabel43.setText("A Java Swing project by:");

        jLabel44.setText("- Apostolidis Mixalis");

        jLabel45.setText("- Kaloudis Alexandros");

        jLabel46.setText("- Pavlidis Giorgos");

        javax.swing.GroupLayout adminHomePageLayout = new javax.swing.GroupLayout(adminHomePage);
        adminHomePage.setLayout(adminHomePageLayout);
        adminHomePageLayout.setHorizontalGroup(
            adminHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminHomePageLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(adminHomeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(adminHomePageLayout.createSequentialGroup()
                .addGroup(adminHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminHomePageLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addGroup(adminHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addGroup(adminHomePageLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel46))))
                    .addGroup(adminHomePageLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel43)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminHomePageLayout.setVerticalGroup(
            adminHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminHomePageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(adminHomeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        adminContent.add(adminHomePage, "card2");

        adminAddUserButton.setText("Add User");
        adminAddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminAddUserButtonActionPerformed(evt);
            }
        });

        adminUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Surname", "Name", "E-mail", "Phone", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(adminUserTable);

        javax.swing.GroupLayout adminUserListPanelLayout = new javax.swing.GroupLayout(adminUserListPanel);
        adminUserListPanel.setLayout(adminUserListPanelLayout);
        adminUserListPanelLayout.setHorizontalGroup(
            adminUserListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminUserListPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(adminUserListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminAddUserButton)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        adminUserListPanelLayout.setVerticalGroup(
            adminUserListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminUserListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminAddUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        adminContent.add(adminUserListPanel, "card3");

        adminBacktoUserListButton.setText("Back");
        adminBacktoUserListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBacktoUserListButtonActionPerformed(evt);
            }
        });

        jLabel23.setText("ID");

        jLabel25.setText("Surname");

        jLabel26.setText("Name");

        jLabel27.setText("Password");

        jLabel28.setText("Address");

        jLabel29.setText("E-mail");

        jLabel30.setText("Phone");

        jLabel31.setText("Year");

        jLabel32.setText("Semester");

        jLabel33.setText("ECTS");

        adminAddStudentYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminAddStudentYearFieldActionPerformed(evt);
            }
        });

        adminAddStudentButton.setText("Add Student");
        adminAddStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminAddStudentButtonActionPerformed(evt);
            }
        });

        adminAddStudentErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout adminAddStudentPanelLayout = new javax.swing.GroupLayout(adminAddStudentPanel);
        adminAddStudentPanel.setLayout(adminAddStudentPanelLayout);
        adminAddStudentPanelLayout.setHorizontalGroup(
            adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminAddStudentIDField)
                    .addComponent(adminAddStudentSurnameField)
                    .addComponent(adminAddStudentNameField)
                    .addComponent(adminAddStudentPasswordField)
                    .addComponent(adminAddStudentAddressField)
                    .addComponent(adminAddStudentEmailField)
                    .addComponent(adminAddStudentPhoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(26, 26, 26)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminAddStudentYearField)
                    .addComponent(adminAddStudentSemesterField)
                    .addComponent(adminAddStudentECTSField, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGap(67, 67, 67))
            .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(adminAddStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(adminAddStudentErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        adminAddStudentPanelLayout.setVerticalGroup(
            adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel31)
                    .addComponent(adminAddStudentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminAddStudentYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel32)
                    .addComponent(adminAddStudentSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminAddStudentSemesterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel33)
                    .addComponent(adminAddStudentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminAddStudentECTSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(adminAddStudentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(adminAddStudentAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(adminAddStudentEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(adminAddStudentPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(adminAddStudentButton)
                .addGap(18, 18, 18)
                .addComponent(adminAddStudentErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Student", adminAddStudentPanel);

        javax.swing.GroupLayout adminAddStaffPanelLayout = new javax.swing.GroupLayout(adminAddStaffPanel);
        adminAddStaffPanel.setLayout(adminAddStaffPanelLayout);
        adminAddStaffPanelLayout.setHorizontalGroup(
            adminAddStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        adminAddStaffPanelLayout.setVerticalGroup(
            adminAddStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("AddStaff", adminAddStaffPanel);

        javax.swing.GroupLayout adminAddAdminPanelLayout = new javax.swing.GroupLayout(adminAddAdminPanel);
        adminAddAdminPanel.setLayout(adminAddAdminPanelLayout);
        adminAddAdminPanelLayout.setHorizontalGroup(
            adminAddAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        adminAddAdminPanelLayout.setVerticalGroup(
            adminAddAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("AddAdmin", adminAddAdminPanel);

        javax.swing.GroupLayout adminAddUserPanelLayout = new javax.swing.GroupLayout(adminAddUserPanel);
        adminAddUserPanel.setLayout(adminAddUserPanelLayout);
        adminAddUserPanelLayout.setHorizontalGroup(
            adminAddUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminAddUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(adminAddUserPanelLayout.createSequentialGroup()
                        .addComponent(adminBacktoUserListButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        adminAddUserPanelLayout.setVerticalGroup(
            adminAddUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminBacktoUserListButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        adminContent.add(adminAddUserPanel, "card4");

        adminAddCourseButton.setText("Add Course");
        adminAddCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminAddCourseButtonActionPerformed(evt);
            }
        });

        adminCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Semester", "ECTS", "Lecturer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(adminCourseTable);

        javax.swing.GroupLayout adminCourseListPanelLayout = new javax.swing.GroupLayout(adminCourseListPanel);
        adminCourseListPanel.setLayout(adminCourseListPanelLayout);
        adminCourseListPanelLayout.setHorizontalGroup(
            adminCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminCourseListPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(adminCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminAddCourseButton)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        adminCourseListPanelLayout.setVerticalGroup(
            adminCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminCourseListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminAddCourseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        adminContent.add(adminCourseListPanel, "card5");

        adminBackToCourseListButton.setText("Back");
        adminBackToCourseListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBackToCourseListButtonActionPerformed(evt);
            }
        });

        jLabel34.setText("ID");

        jLabel35.setText("Name");

        jLabel36.setText("Semester");

        jLabel37.setText("ECTS");

        jLabel38.setText("Lecturer");

        jLabel39.setText("Info");

        adminAddCourseInfoField.setColumns(20);
        adminAddCourseInfoField.setRows(5);
        jScrollPane3.setViewportView(adminAddCourseInfoField);

        adminAddCourseFinalButton.setText("Add Course");
        adminAddCourseFinalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminAddCourseFinalButtonActionPerformed(evt);
            }
        });

        adminAddCourseSemesterField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H" }));

        adminAddCourseErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout adminAddCoursePanelLayout = new javax.swing.GroupLayout(adminAddCoursePanel);
        adminAddCoursePanel.setLayout(adminAddCoursePanelLayout);
        adminAddCoursePanelLayout.setHorizontalGroup(
            adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                        .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminBackToCourseListButton)
                            .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                                .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38))
                                .addGap(45, 45, 45)
                                .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminAddCourseErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(adminAddCourseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminAddCourseIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminAddCourseECTSField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                        .addComponent(adminAddCourseLecturerField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(adminAddCourseSemesterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(261, Short.MAX_VALUE))
                    .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminAddCourseFinalButton)
                        .addGap(96, 96, 96))))
        );
        adminAddCoursePanelLayout.setVerticalGroup(
            adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminAddCourseFinalButton)
                    .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                        .addComponent(adminBackToCourseListButton)
                        .addGap(18, 18, 18)
                        .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(adminAddCourseIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(adminAddCourseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(adminAddCourseSemesterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(adminAddCourseECTSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(adminAddCourseLecturerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminAddCourseErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        adminContent.add(adminAddCoursePanel, "card6");

        mainAdmin.add(adminContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 710, 460));

        logoutButtonAdmin.setText("Logout");
        logoutButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonAdminActionPerformed(evt);
            }
        });
        mainAdmin.add(logoutButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 40));

        adminLogo.setIcon(mini);
        adminLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLogoMouseClicked(evt);
            }
        });
        mainAdmin.add(adminLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, 50));

        adminUserListButton.setText("User List");
        adminUserListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUserListButtonActionPerformed(evt);
            }
        });
        mainAdmin.add(adminUserListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, -1));

        adminCourseListButton.setText("Course List");
        adminCourseListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCourseListButtonActionPerformed(evt);
            }
        });
        mainAdmin.add(adminCourseListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, -1));

        jLayeredPane1.add(mainAdmin, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        getAccessibleContext().setAccessibleName("loginFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        for(Object i : db.userDB){
            if(((loginIDField.getText().equals(((user) i).getId()))) && (((user)i).getPassword().equals(new String (loginPasswordField.getPassword())))) {
                if(i instanceof student){
                    loginScreen.setVisible(false);
                    mainStudent.setVisible(true);
                    studentLayout.show(studentContent, "studentHomePage");
                }
                else if(i instanceof staff){
                    loginScreen.setVisible(false);
                    mainStaff.setVisible(true);
                    staffLayout.show(staffContent,"staffHomePage");
                    
                }
                else if(i instanceof administration){
                    loginScreen.setVisible(false);
                    mainAdmin.setVisible(true);
                    adminLayout.show(adminContent,"adminHomePage");
                }
                loginIDField.setText("");
                loginPasswordField.setText("");
                loginErrorMessage.setText("");
                loggedUser = (user)i;
                break;
            } 
            else {
                loginErrorMessage.setText("User does not exist");
                
            }
        
        }
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordFieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_loginPasswordFieldActionPerformed

    private void loginIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIDFieldActionPerformed

    private void logoutButtonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonStudentActionPerformed
        loginScreen.setVisible(true);
        mainStudent.setVisible(false);
    }//GEN-LAST:event_logoutButtonStudentActionPerformed

    private void loginPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginPasswordFieldKeyPressed
        //login with enter button from password form
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           loginButton.doClick();
        }
        
    }//GEN-LAST:event_loginPasswordFieldKeyPressed

    private void loginIDFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginIDFieldKeyPressed
        //login with enter button from password form
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           loginButton.doClick();
        }
    }//GEN-LAST:event_loginIDFieldKeyPressed

    private void studentDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDetailsButtonActionPerformed
        studentDetailNameLabel.setText(((student)loggedUser).getName());
        studentDetailSurnameLabel.setText(((student)loggedUser).getSurname());
        studentDetailPhoneLabel.setText(Integer.toString(((student)loggedUser).getPhone()));
        studentDetailAddressLabel.setText(((student)loggedUser).getAddress());
        studentDetailEmailLabel.setText(((student)loggedUser).getEmail());
        studentDetailIDLabel.setText(((student)loggedUser).getId());
        studentDetailSemesterLabel.setText(((student)loggedUser).getSemester());
        studentDetailYearLabel.setText(Integer.toString(((student)loggedUser).getEtosEisagosis()));
        studentDetailECTSLabel.setText(Integer.toString(((student)loggedUser).getECTS()));
        
        studentLayout.show(studentContent, "studentDetailsPanel");
        
    }//GEN-LAST:event_studentDetailsButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        studentLayout.show(studentContent, "jPanel3");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonStaffActionPerformed
        loginScreen.setVisible(true);
        mainStaff.setVisible(false);
    }//GEN-LAST:event_logoutButtonStaffActionPerformed

    private void logoutButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonAdminActionPerformed
        loginScreen.setVisible(true);
        mainAdmin.setVisible(false);
    }//GEN-LAST:event_logoutButtonAdminActionPerformed

    private void staffDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffDetailsButtonActionPerformed
        staffDetailNameLabel.setText(((staff)loggedUser).getName());
        staffDetailSurnameLabel.setText(((staff)loggedUser).getSurname());
        staffDetailPhoneLabel.setText(Integer.toString(((staff)loggedUser).getPhone()));
        staffDetailAddressLabel.setText(((staff)loggedUser).getAddress());
        staffDetailEmailLabel.setText(((staff)loggedUser).getEmail());
        staffDetailIDlabel.setText(((staff)loggedUser).getId());
        
        
        staffLayout.show(staffContent, "staffDetailsPanel"); 
    }//GEN-LAST:event_staffDetailsButtonActionPerformed

    private void adminLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLogoMouseClicked
        //go to admin home page
       adminLayout.show(adminContent,"adminHomePage"); 
    }//GEN-LAST:event_adminLogoMouseClicked

    private void staffLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffLogoMouseClicked
        // go to staff home page
        staffLayout.show(staffContent,"staffHomePage");
    }//GEN-LAST:event_staffLogoMouseClicked

    private void studentLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLogoMouseClicked
        //go to student home page
        studentLayout.show(studentContent, "studentHomePage");
    }//GEN-LAST:event_studentLogoMouseClicked

    private void staffUserListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffUserListButtonActionPerformed
        DefaultTableModel staffUserDTable = (DefaultTableModel) staffUserTable.getModel();
        staffUserDTable.setRowCount(0);
        for(Object i : db.userDB){           
            staffUserDTable.addRow(new Object[]{((user)i).getId(),((user)i).getSurname(),((user)i).getName(),((user)i).getEmail()});
            
            }
        
        staffLayout.show(staffContent,"staffUserListPanel");
    }//GEN-LAST:event_staffUserListButtonActionPerformed

    private void adminUserListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUserListButtonActionPerformed
        DefaultTableModel adminUserDTable = (DefaultTableModel) adminUserTable.getModel();
        adminUserDTable.setRowCount(0);
        for(Object i : db.userDB){           
            adminUserDTable.addRow(new Object[]{((user)i).getId(),((user)i).getSurname(),((user)i).getName(),((user)i).getEmail(),((user)i).getPhone(),((user)i).getAddress()});
            
            }
        
        adminLayout.show(adminContent,"adminUserListPanel");
    }//GEN-LAST:event_adminUserListButtonActionPerformed

    private void adminBacktoUserListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBacktoUserListButtonActionPerformed
        this.adminUserListButton.doClick();
    }//GEN-LAST:event_adminBacktoUserListButtonActionPerformed

    private void adminAddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminAddUserButtonActionPerformed
        adminLayout.show(adminContent,"adminAddUserPanel");
    }//GEN-LAST:event_adminAddUserButtonActionPerformed

    private void adminAddStudentYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminAddStudentYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminAddStudentYearFieldActionPerformed

    private void adminAddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminAddStudentButtonActionPerformed
        if(adminAddStudentIDField.equals("") || adminAddStudentSurnameField.equals("") || adminAddStudentNameField.equals("") || adminAddStudentPasswordField.equals("") || adminAddStudentAddressField.equals("") || adminAddStudentEmailField.equals("") || adminAddStudentNameField.equals("") || adminAddStudentPhoneField.equals("") || adminAddStudentYearField.equals("") || adminAddStudentSemesterField.equals("") || adminAddStudentECTSField.equals(""))
            adminAddStudentErrorMessage.setText("Please fill in all the fields");
        else
        {
            db.userDB.add(new student(adminAddStudentIDField.getText(),adminAddStudentNameField.getText(),adminAddStudentSurnameField.getText(),adminAddStudentPasswordField.getText(),adminAddStudentAddressField.getText(),adminAddStudentEmailField.getText(),Integer.valueOf(adminAddStudentPhoneField.getText()),Integer.valueOf(adminAddStudentYearField.getText()),adminAddStudentSemesterField.getText(),Integer.valueOf(adminAddStudentECTSField.getText())));
            adminAddStudentErrorMessage.setText("");
            db.serializeUsers("./data/obj.ser");
        }                 
    }//GEN-LAST:event_adminAddStudentButtonActionPerformed

    private void adminBackToCourseListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBackToCourseListButtonActionPerformed
        this.adminCourseListButton.doClick();
    }//GEN-LAST:event_adminBackToCourseListButtonActionPerformed

    private void adminCourseListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCourseListButtonActionPerformed
        DefaultTableModel adminCourseDTable = (DefaultTableModel) adminCourseTable.getModel();
        adminCourseDTable.setRowCount(0);
        for(Object i : db.courseDB){
            adminCourseDTable.addRow(new Object[]{((course)i).getId(),((course)i).getName(),((course)i).getSemester(),((course)i).getECTS(),((course)i).getTeacher().getSurname() + " " + ((course)i).getTeacher().getName()});
        }
        adminLayout.show(adminContent,"adminCourseListPanel");
        
    }//GEN-LAST:event_adminCourseListButtonActionPerformed

     
    private void adminAddCourseFinalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminAddCourseFinalButtonActionPerformed
        staff tempstaff=null; 
        if(adminAddCourseIDField.getText().equals("") || adminAddCourseNameField.getText().equals("") || adminAddCourseECTSField.getText().equals("") || adminAddCourseInfoField.getText().equals(""))
            adminAddCourseErrorMessage.setText("Please fill in all the fields");
        else
        {
            int index = 0;
            String staffID="";
            
            do{
                staffID+=adminAddCourseLecturerField.getSelectedItem().toString().charAt(index);
                index++;
            }
            while(adminAddCourseLecturerField.getSelectedItem().toString().charAt(index) != ' ');
            for (Object i : db.userDB){
                if(((user)i).getId().equals(staffID)){
                    tempstaff=(staff)i;
                    break;
                }
            }
        db.courseDB.add(new course(adminAddCourseIDField.getText(),adminAddCourseNameField.getText(),adminAddCourseSemesterField.getSelectedItem().toString(),Integer.valueOf(adminAddCourseECTSField.getText()),tempstaff,adminAddCourseInfoField.getText()));
        adminAddCourseIDField.setText("");
        adminAddCourseNameField.setText("");
        adminAddCourseSemesterField.setSelectedIndex(0);
        adminAddCourseECTSField.setText("");
        adminAddCourseInfoField.setText("");
        adminAddCourseErrorMessage.setText("");
        db.serializeCourses("./data/courses.ser");    
                
        }
            
        
    }//GEN-LAST:event_adminAddCourseFinalButtonActionPerformed

    private void adminAddCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminAddCourseButtonActionPerformed
        adminAddCourseLecturerField.removeAllItems();
        for (Object i : db.userDB){
            if(i instanceof staff){
                adminAddCourseLecturerField.addItem(((staff)i).getId() + " " + ((staff)i).getSurname() + " " + ((staff)i).getName());
            }
        }
        adminLayout.show(adminContent,"adminAddCoursePanel");
    }//GEN-LAST:event_adminAddCourseButtonActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    
    
    static dbHelper db = new dbHelper();
    ImageIcon mini = new ImageIcon("./images/logo-Mini.png");
    CardLayout studentLayout;
    CardLayout staffLayout;
    CardLayout adminLayout;
    user loggedUser;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
                db.deserializeCourses("./data/courses.ser");
                db.deserializeUsers("./data/obj.ser");
                /*
                student s1 = new student("123456","Georgios","Pavlidis","123456789","Papandreou 5","GeorgePaul@gmail.com",694123123,2017,"H",160);
                staff s2= new staff("741852963","Mike","Apostolidis","15948756","Vasilis Olgas 90","MikeApostolidis@gmail.com",694789123);
                administration a1 = new administration("admin","grammateia","suregrammateia","admin123","Sindos 10","grammateia@teithe.gr",23101234);
                
                
                db.writeUser(s1.toString(),"./data/userlist.txt");
                db.writeUser(s2.toString(),"./data/userlist.txt");
                db.writeUser(a1.toString(),"./data/userlist.txt");
                
                db.userDB.add(s1);
                db.userDB.add(s2);
                db.userDB.add(a1);
                
                db.serializeUsers("./data/obj.ser"); 
                */
                /*
                staff s2= new staff("741852963","Mike","Apostolidis","15948756","Vasilis Olgas 90","MikeApostolidis@gmail.com",694789123);
                course c1 = new course("101","Java 1","A",6,s2,"Info 2");
                course c2 = new course("201","Java 2","B",6,s2,"Info 2");
                
                
                db.courseDB.add(c1);
                db.courseDB.add(c2);
                
                
                db.serializeCourses("./data/courses.ser");
                */
                
                
               
                
            }
        });   
        
        
        
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminAddAdminPanel;
    private javax.swing.JButton adminAddCourseButton;
    private javax.swing.JTextField adminAddCourseECTSField;
    private javax.swing.JLabel adminAddCourseErrorMessage;
    private javax.swing.JButton adminAddCourseFinalButton;
    private javax.swing.JTextField adminAddCourseIDField;
    private javax.swing.JTextArea adminAddCourseInfoField;
    private javax.swing.JComboBox<String> adminAddCourseLecturerField;
    private javax.swing.JTextField adminAddCourseNameField;
    private javax.swing.JPanel adminAddCoursePanel;
    private javax.swing.JComboBox<String> adminAddCourseSemesterField;
    private javax.swing.JPanel adminAddStaffPanel;
    private javax.swing.JTextField adminAddStudentAddressField;
    private javax.swing.JButton adminAddStudentButton;
    private javax.swing.JTextField adminAddStudentECTSField;
    private javax.swing.JTextField adminAddStudentEmailField;
    private javax.swing.JLabel adminAddStudentErrorMessage;
    private javax.swing.JTextField adminAddStudentIDField;
    private javax.swing.JTextField adminAddStudentNameField;
    private javax.swing.JPanel adminAddStudentPanel;
    private javax.swing.JTextField adminAddStudentPasswordField;
    private javax.swing.JTextField adminAddStudentPhoneField;
    private javax.swing.JTextField adminAddStudentSemesterField;
    private javax.swing.JTextField adminAddStudentSurnameField;
    private javax.swing.JTextField adminAddStudentYearField;
    private javax.swing.JButton adminAddUserButton;
    private javax.swing.JPanel adminAddUserPanel;
    private javax.swing.JButton adminBackToCourseListButton;
    private javax.swing.JButton adminBacktoUserListButton;
    private javax.swing.JPanel adminContent;
    private javax.swing.JButton adminCourseListButton;
    private javax.swing.JPanel adminCourseListPanel;
    private javax.swing.JTable adminCourseTable;
    private javax.swing.JLabel adminHomeLogo;
    private javax.swing.JPanel adminHomePage;
    private javax.swing.JLabel adminLogo;
    private javax.swing.JButton adminUserListButton;
    private javax.swing.JPanel adminUserListPanel;
    private javax.swing.JTable adminUserTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginErrorMessage;
    private javax.swing.JTextField loginIDField;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JButton logoutButtonAdmin;
    private javax.swing.JButton logoutButtonStaff;
    private javax.swing.JButton logoutButtonStudent;
    private javax.swing.JPanel mainAdmin;
    private javax.swing.JPanel mainStaff;
    private javax.swing.JPanel mainStudent;
    private javax.swing.JPanel staffContent;
    private javax.swing.JLabel staffDetailAddressLabel;
    private javax.swing.JLabel staffDetailEmailLabel;
    private javax.swing.JLabel staffDetailIDlabel;
    private javax.swing.JLabel staffDetailNameLabel;
    private javax.swing.JLabel staffDetailPhoneLabel;
    private javax.swing.JLabel staffDetailSurnameLabel;
    private javax.swing.JButton staffDetailsButton;
    private javax.swing.JPanel staffDetailsPanel;
    private javax.swing.JLabel staffHomeLogo;
    private javax.swing.JPanel staffHomePage;
    private javax.swing.JLabel staffLogo;
    private javax.swing.JButton staffUserListButton;
    private javax.swing.JPanel staffUserListPanel;
    private javax.swing.JTable staffUserTable;
    private javax.swing.JPanel studentContent;
    private javax.swing.JLabel studentDetailAddressLabel;
    private javax.swing.JLabel studentDetailECTSLabel;
    private javax.swing.JLabel studentDetailEmailLabel;
    private javax.swing.JLabel studentDetailIDLabel;
    private javax.swing.JLabel studentDetailNameLabel;
    private javax.swing.JLabel studentDetailPhoneLabel;
    private javax.swing.JLabel studentDetailSemesterLabel;
    private javax.swing.JLabel studentDetailSurnameLabel;
    private javax.swing.JLabel studentDetailYearLabel;
    private javax.swing.JButton studentDetailsButton;
    private javax.swing.JPanel studentDetailsPanel;
    private javax.swing.JLabel studentHomeLogo;
    private javax.swing.JPanel studentHomePage;
    private javax.swing.JLabel studentLogo;
    // End of variables declaration//GEN-END:variables
}
