import javax.swing.ImageIcon;


public class main extends javax.swing.JFrame {

    /**
     * Creates new form loginScreen
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        loginScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginIDField = new javax.swing.JTextField();
        loginPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        loginLogo = new javax.swing.JLabel();
        loginErrorMessage = new javax.swing.JLabel();
        mainStudent = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        mainStaff = new javax.swing.JPanel();
        mainAdmin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 204));
        setForeground(new java.awt.Color(204, 0, 204));
        setName("loginFrame"); // NOI18N

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        loginScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        loginScreen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, 20));

        jLabel2.setText("Password");
        loginScreen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 110, 20));

        loginIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIDFieldActionPerformed(evt);
            }
        });
        loginScreen.add(loginIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 170, 30));

        loginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordFieldActionPerformed(evt);
            }
        });
        loginScreen.add(loginPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 170, 30));

        loginButton.setText("Login");
        loginButton.setActionCommand("loginButton");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginScreen.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 140, 30));
        loginButton.getAccessibleContext().setAccessibleName("loginButton");

        loginScreen.add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 520, 190));
        ImageIcon icon = new ImageIcon("./images/logo-Main.png");
        loginLogo.setIcon(icon);

        loginErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        loginScreen.add(loginErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 330, 20));

        jLayeredPane1.add(loginScreen, "card2");

        mainStudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        mainStudent.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, 40));

        jLayeredPane1.add(mainStudent, "card3");

        javax.swing.GroupLayout mainStaffLayout = new javax.swing.GroupLayout(mainStaff);
        mainStaff.setLayout(mainStaffLayout);
        mainStaffLayout.setHorizontalGroup(
            mainStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        mainStaffLayout.setVerticalGroup(
            mainStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jLayeredPane1.add(mainStaff, "card4");

        javax.swing.GroupLayout mainAdminLayout = new javax.swing.GroupLayout(mainAdmin);
        mainAdmin.setLayout(mainAdminLayout);
        mainAdminLayout.setHorizontalGroup(
            mainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        mainAdminLayout.setVerticalGroup(
            mainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jLayeredPane1.add(mainAdmin, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        getAccessibleContext().setAccessibleName("loginFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        for(Object i : db.list){
            if(((loginIDField.getText().equals(((user) i).getId()))) && (((user)i).getPassword().equals(new String (loginPasswordField.getPassword())))) {
                if(i instanceof student){
                    loginScreen.setVisible(false);
                    mainStudent.setVisible(true);
                }
                else if(i instanceof staff){
                    loginScreen.setVisible(false);
                    mainStaff.setVisible(true);
                }
                else if(i instanceof administration){
                    loginScreen.setVisible(false);
                    mainAdmin.setVisible(true);
                }
                break;
            } 
            else {
                loginErrorMessage.setText("User does not exist");
                
            }
        
        }
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPasswordFieldActionPerformed

    private void loginIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIDFieldActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        loginScreen.setVisible(true);
        mainStudent.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    
    
    static dbHelper db = new dbHelper();
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
                db.deserializeFromFile("./data/obj.ser");
                /*
                student s1 = new student("123456","Pavlidis","123456789");
                staff s2= new staff("741852963","Mike","15948756");
                administration a1 = new administration("admin","grammateia","admin123");
                
                db.list.add(s1);
                db.list.add(s2);
                db.list.add(a1);
                
                db.serializeToFile(db.list, "./data/obj.ser");
                */
            }
        });
        
        
        
        //Example write to userlist      
        
        /*
        student s1 = new student("123456","Pavlidis","123456789");
        staff s2= new staff("741852963","Mike","15948756");
        /*
        db.writeUser(s1.toString());
        db.writeUser(s2.toString());
        
        //Example Serialize List
        
        db.addUserList(s1);
        db.addUserList(s2);
        db.serializeToFile(db.list);
        
        //Example Load Serialized List
        
        
        
        
        for(Object i : db.list){
            System.out.println(((user)i).toString());
        }
        */
        
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginErrorMessage;
    private javax.swing.JTextField loginIDField;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainAdmin;
    private javax.swing.JPanel mainStaff;
    private javax.swing.JPanel mainStudent;
    // End of variables declaration//GEN-END:variables
}
