import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import java.awt.CardLayout;


public class main extends javax.swing.JFrame  {

    /**
     * Creates new form loginScreen
     */
    public main() {
        initComponents();
        studentLayout = (CardLayout)(studentContent.getLayout());
        studentLayout.addLayoutComponent(studentHomePage, "studentHomePage");
        studentLayout.addLayoutComponent(jPanel2, "jPanel2");
        studentLayout.addLayoutComponent(jPanel3, "jPanel3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        loginScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginIDField = new javax.swing.JTextField();
        loginPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        loginLogo = new javax.swing.JLabel();
        loginErrorMessage = new javax.swing.JLabel();
        mainStudent = new javax.swing.JPanel();
        logoutButtonStudent = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        studentContent = new javax.swing.JPanel();
        studentHomePage = new javax.swing.JPanel();
        studentHomeLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mainStaff = new javax.swing.JPanel();
        staffContent = new javax.swing.JPanel();
        logoutButtonStaff = new javax.swing.JButton();
        mainAdmin = new javax.swing.JPanel();
        adminContent = new javax.swing.JPanel();
        logoutButtonAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 204));
        setForeground(new java.awt.Color(204, 0, 204));
        setName("loginFrame"); // NOI18N

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        loginScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        loginScreen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, 20));

        jLabel2.setText("Password");
        loginScreen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 110, 20));

        loginIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIDFieldActionPerformed(evt);
            }
        });
        loginIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginIDFieldKeyPressed(evt);
            }
        });
        loginScreen.add(loginIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 170, 30));

        loginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordFieldActionPerformed(evt);
            }
        });
        loginPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginPasswordFieldKeyPressed(evt);
            }
        });
        loginScreen.add(loginPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 170, 30));

        loginButton.setText("Login");
        loginButton.setActionCommand("loginButton");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginScreen.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 140, 30));
        loginButton.getAccessibleContext().setAccessibleName("loginButton");

        loginScreen.add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 520, 190));
        ImageIcon icon = new ImageIcon("./images/logo-Main.png");
        loginLogo.setIcon(icon);

        loginErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        loginScreen.add(loginErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 330, 20));

        jLayeredPane1.add(loginScreen, "card2");

        mainStudent.setBackground(new java.awt.Color(153, 153, 153));
        mainStudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButtonStudent.setText("Logout");
        logoutButtonStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonStudentActionPerformed(evt);
            }
        });
        mainStudent.add(logoutButtonStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 40));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainStudent.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainStudent.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        studentContent.setLayout(new java.awt.CardLayout());

        jLabel5.setText("A Java Swing project by");

        jLabel6.setText("- Apostolidis Mixalis -");

        jLabel7.setText("- Kaloudis Alexandros - ");

        jLabel8.setText("- Pavlidis Giorgos -");

        javax.swing.GroupLayout studentHomePageLayout = new javax.swing.GroupLayout(studentHomePage);
        studentHomePage.setLayout(studentHomePageLayout);
        studentHomePageLayout.setHorizontalGroup(
            studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentHomePageLayout.createSequentialGroup()
                .addGroup(studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentHomePageLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(studentHomePageLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel6)))))
                    .addGroup(studentHomePageLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentHomePageLayout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addComponent(studentHomeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        studentHomePageLayout.setVerticalGroup(
            studentHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentHomePageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(studentHomeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        studentHomeLogo.setIcon(icon);

        studentContent.add(studentHomePage, "card4");

        jLabel3.setText("Panel 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        studentContent.add(jPanel2, "card2");

        jLabel4.setText("Panel 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        studentContent.add(jPanel3, "card3");

        mainStudent.add(studentContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 710, 460));

        jLayeredPane1.add(mainStudent, "card3");

        mainStaff.setBackground(new java.awt.Color(153, 153, 153));
        mainStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffContent.setLayout(new java.awt.CardLayout());
        mainStaff.add(staffContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 710, 460));

        logoutButtonStaff.setText("Logout");
        logoutButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonStaffActionPerformed(evt);
            }
        });
        mainStaff.add(logoutButtonStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 40));

        jLayeredPane1.add(mainStaff, "card4");

        mainAdmin.setBackground(new java.awt.Color(153, 153, 153));
        mainAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminContent.setLayout(new java.awt.CardLayout());
        mainAdmin.add(adminContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 710, 460));

        logoutButtonAdmin.setText("Logout");
        logoutButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonAdminActionPerformed(evt);
            }
        });
        mainAdmin.add(logoutButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 40));

        jLayeredPane1.add(mainAdmin, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        getAccessibleContext().setAccessibleName("loginFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        for(Object i : db.userDB){
            if(((loginIDField.getText().equals(((user) i).getId()))) && (((user)i).getPassword().equals(new String (loginPasswordField.getPassword())))) {
                if(i instanceof student){
                    loginScreen.setVisible(false);
                    mainStudent.setVisible(true);
                }
                else if(i instanceof staff){
                    loginScreen.setVisible(false);
                    mainStaff.setVisible(true);
                }
                else if(i instanceof administration){
                    loginScreen.setVisible(false);
                    mainAdmin.setVisible(true);
                }
                loginIDField.setText("");
                loginPasswordField.setText("");
                loginErrorMessage.setText("");
                break;
            } 
            else {
                loginErrorMessage.setText("User does not exist");
                
            }
        
        }
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordFieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_loginPasswordFieldActionPerformed

    private void loginIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIDFieldActionPerformed

    private void logoutButtonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonStudentActionPerformed
        loginScreen.setVisible(true);
        mainStudent.setVisible(false);
    }//GEN-LAST:event_logoutButtonStudentActionPerformed

    private void loginPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginPasswordFieldKeyPressed
        //login with enter button from password form
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           loginButton.doClick();
        }
        
    }//GEN-LAST:event_loginPasswordFieldKeyPressed

    private void loginIDFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginIDFieldKeyPressed
        //login with enter button from password form
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           loginButton.doClick();
        }
    }//GEN-LAST:event_loginIDFieldKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        studentLayout.show(studentContent, "jPanel2");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        studentLayout.show(studentContent, "jPanel3");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonStaffActionPerformed
        loginScreen.setVisible(true);
        mainStaff.setVisible(false);
    }//GEN-LAST:event_logoutButtonStaffActionPerformed

    private void logoutButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonAdminActionPerformed
        loginScreen.setVisible(true);
        mainAdmin.setVisible(false);
    }//GEN-LAST:event_logoutButtonAdminActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    
    
    static dbHelper db = new dbHelper();
    CardLayout studentLayout;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
                db.deserializeUsers("./data/obj.ser");
                /*
                student s1 = new student("123456","Pavlidis","123456789");
                staff s2= new staff("741852963","Mike","15948756");
                administration a1 = new administration("admin","grammateia","admin123");
                
                db.userDB.add(s1);
                db.userDB.add(s2);
                db.userDB.add(a1);
                
                db.serializeUsers("./data/obj.ser");
                */
            }
        });
        
        
        
        //Example write to userlist      
        
        /*
        student s1 = new student("123456","Pavlidis","123456789");
        staff s2= new staff("741852963","Mike","15948756");
        /*
        db.writeUser(s1.toString());
        db.writeUser(s2.toString());
        
        //Example Serialize List
        
        db.addUserList(s1);
        db.addUserList(s2);
        db.serializeToFile(db.list);
        
        //Example Load Serialized List
        
        
        
        
        for(Object i : db.userDB){
            System.out.println(((user)i).toString());
        }
        */
        
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminContent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginErrorMessage;
    private javax.swing.JTextField loginIDField;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JButton logoutButtonAdmin;
    private javax.swing.JButton logoutButtonStaff;
    private javax.swing.JButton logoutButtonStudent;
    private javax.swing.JPanel mainAdmin;
    private javax.swing.JPanel mainStaff;
    private javax.swing.JPanel mainStudent;
    private javax.swing.JPanel staffContent;
    private javax.swing.JPanel studentContent;
    private javax.swing.JLabel studentHomeLogo;
    private javax.swing.JPanel studentHomePage;
    // End of variables declaration//GEN-END:variables
}
